feature: update enforcer FORMAT

diff --git a/.github/workflows/enforcer.yml b/.github/workflows/enforcer.yml
--- a/.github/workflows/enforcer.yml
+++ b/.github/workflows/enforcer.yml
@@ -6,11 +6,11 @@ on:
 
 jobs:
     check_branch:
-        if: contains(fromJson('["master", "main"]'), github.base_ref) && github.head_ref != 'develop'      
+        if: contains(fromJson('["master", "main"]'), github.base_ref) && github.head_ref != 'develop'
         runs-on: ubuntu-latest
         steps:
-            - name: Disable merging
-                run: |
-                    echo github.base_ref
-                    echo "ERROR: You can only merge to main from develop."
-                    exit 1
+            - name: Stop merging
+              run: |
+                  echo github.base_ref
+                  echo "ERROR: You can only merge to main from develop."
+                  exit 1
